spring:
  datasource:
    newauthdb: # 5.7
      driver-class-name: com.mysql.cj.jdbc.Driver
      jdbc-url: jdbc:mysql://172.16.0.140:3306/auth?serverTimezone=Asia/Seoul&useSSL=false
      username: unimoa
      password: pwunimoa
server:
  port: 19015
#logging:
#  config: classpath:logback.xml